# Change these first
owner: chaotic-art # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  # App Domain
  - name: Chaotic Art
    url: https://chaotic.art

  # Services
  - name: Price Service
    url: https://price.chaotic.art
  - name: Genart Service
    url: https://genart.chaotic.art
  - name: Profile Service
    url: https://profile.chaotic.art
  - name: Bucket Service
    url: https://bucket.chaotic.art/
  - name: Dyndata Service
    url: https://dyndata.chaotic.art
  - name: ODA Service
    url: https://oda.chaotic.art
  - name: Playground Bucket Service
    url: https://playground-bucket.chaotic.art/codeChecker/04a8f6c9-07b0-40ec-88ab-e6c8789c9fe4.html?hash=0xdb736faf90adce01428200c2232bc6d9ecfb539d1d2f8451921a65c9e1cb567e
  - name: NFT Storage (IPOS)
    url: https://ipos.chaotic.art

  # GraphQL Endpoints
  # - name: Speck GraphQL
  #   url: https://chaotic.squids.live/speck@v16/api/graphql
  # - name: Stick GraphQL
  #   url: https://chaotic.squids.live/stick@v14/api/graphql
  - name: Stellate AHK
    url: https://chaotic-ahk.stellate.sh/
  - name: Stellate AHP
    url: https://chaotic-ahp.stellate.sh/

  # GraphQL Endpoints (POST)
  # - name: Speck GraphQL (POST)
  #   url: https://chaotic.squids.live/speck@v16/api/graphql
  #   method: POST
  #   headers:
  #     Content-Type: application/json
  #   body: '{"query":"{ squidStatus { height hash finalizedHeight finalizedHash } }"}'
  # - name: Stick GraphQL (POST)
  #   url: https://chaotic.squids.live/stick@v14/api/graphql
  #   method: POST
  #   headers:
  #     Content-Type: application/json
  #   body: '{"query":"{ squidStatus { height hash finalizedHeight finalizedHash } }"}'
  - name: Stellate AHK (POST)
    url: https://chaotic-ahk.stellate.sh/
    method: POST
    headers:
      Content-Type: application/json
    body: '{"query":"{ squidStatus { height hash finalizedHeight finalizedHash } }"}'
  - name: Stellate AHP (POST)
    url: https://chaotic-ahp.stellate.sh/
    method: POST
    headers:
      Content-Type: application/json
    body: '{"query":"{ squidStatus { height hash finalizedHeight finalizedHash } }"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.chaotic.art
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/chaotic-art/uptime/master/assets/upptime-icon.svg
  name: Chaotic Art Status
  introTitle: "**Chaotic Art** Service Status"
  introMessage: Real-time status monitoring for Chaotic Art services powered by [Upptime](https://upptime.js.org).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
